name: actions
on:
  push:
    branches:
      - master
      - feature-qemu-10
    paths:
      - containers/**
      - .github/workflows/actions.yml
      - "*.sh"
  pull_request:
    branches:
      - master
    paths:
      - containers/**
      - .github/workflows/actions.yml
      - "*.sh"
jobs:
  qemu-user-static:
    runs-on: ubuntu-latest
    env:
      VERSION: 10.0.2
      ORIGIN_VERSION: 10.0.0+ds-2~bpo12+2
    steps:
      - uses: actions/checkout@v2
      - name: Set variables
        run: |
          echo "DOCKER_REPO=docker.io/$GITHUB_REPOSITORY" >> $GITHUB_ENV
      - name: Prepare Build
        run: |
          # Debian mirrors backed by Fastly CDN
          # https://ftp.debian.org/
          # wget --content-disposition http://cdn-fastly.deb.debian.org/debian/pool/main/q/qemu/qemu-user-static_${{ env.ORIGIN_VERSION }}_amd64.deb
          wget --content-disposition http://deb.debian.org/debian/pool/main/q/qemu/qemu-user-static_${{ env.ORIGIN_VERSION }}_amd64.deb
          dpkg-deb -R qemu-user-static_*.deb releases
          ls -lha releases
          ls -lha releases/DEBIAN/
          ls -lha releases/usr/bin/
          du -h -d 1 releases/usr/bin/
          ls -lha releases/usr/bin/qemu-aarch64-static
          file releases/usr/bin/qemu-aarch64-static
      - name: Build
        run: |
          ./run.sh -t "${{ env.VERSION }}" -r "${{ env.GITHUB_REPOSITORY }}" -d "${{ env.DOCKER_REPO }}"
      - name: Test
        run: ./test.sh -d "${{ env.DOCKER_REPO }}"
      - name: Publish
        if: ${{ 0 && github.ref == 'refs/heads/master' }}
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker push --all-tags ${{ env.DOCKER_REPO }}
      - name: Create Release
        if: github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          name: "v${{ env.VERSION }}"
          tag: "v${{ env.VERSION }}"
          body: |
            # `qemu-*-static` @ ${{ env.VERSION }}
          artifacts: "releases/usr/bin/*.tar.gz,releases/usr/bin/qemu-*-static"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
